server:
  port: 7003


#Eurake
eureka:
  instance:
    hostname: localhost  #服务端的名称
  client:
    register-with-eureka: false #是否向eureka注册中心注册自己
    fetch-registry: false #为false代表自己为注册中心
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/
