server:
  port: 3344
spring:
  application:
    name: springcloud-springcloud-server-3344
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/zhang-bolin/demo.git #https , 不是svn

#通过config-server 可以连接到git,访问其中的资源或者配置